# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development

on:
  pull_request:
    branches:
      - main

env:
  ## Sets environment variable
  PORT: 5000
  GRAPH_API_TOKEN: 'GRAPH_API_TOKEN'
  GRAPH_PHONE_NUMBER_ID: '123456789098765'
  WEBHOOK_VERIFY_TOKEN: 'WEB_HOOK_VERIFY_TOKEN'
  WB_URL: 'https://api.whatsapp.com/'
  TWITTER_API_KEY: 'TWITTER_API_KEY'
  TWITTER_API_SECRET: 'TWITTER_API_SECRET'
  TWITTER_ACCESS_TOKEN: 'TWITTER_ACCESS_TOKEN'
  TWITTER_ACCESS_TOKEN_SECRET: 'TWITTER_ACCESS_TOKEN_SECRET'
  BSKY_IDENTIFIER: 'BSKY_IDENTIFIER'
  BSKY_PASSWORD: 'BSKY_PASSWORD'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

        # ESLint and Prettier must be in `package.json`
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test

  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Running integration tests
        run: yarn test:e2e
